### PR TITLE
custom data message under data-msg

### PR DESCRIPTION
**Pull request by tyler-dunkel**

### CODE REVIEW

**Comment by AdamBrodzinski** [comment]
Awesome! I'm going to try test and merge this in tonight. Thanks! :beers:

**Comment by tyler-dunkel** [comment]
Ok just so you know I didn't test toooo throughly :p hopefully it works.

**Comment by AdamBrodzinski** [comment]
Thanks @tdmoneybanks !

**Comment by tyler-dunkel** [comment]
no problem glad to help! can you update the package on atmosphere as well? Thanks.

**Comment by AdamBrodzinski** [comment]
Yep! will push that in a few mins.

**Pull request merged**
